### ISSUE TITLE
Where should i place jar file?

### ISSUE THREAD

**Issue by StCremer** [m-click/mcpdf#11]
Sorry, I'm new at linux. Could you please tell me where should i place mcpdf.jar? 
when testing "java -jar mcpdf.jar"  i get "Error: Unable to access jarfile mcpdf.jar"

**Comment by vog** [comment]
You should run the command it in the same directory in which you put the `mcpdf.jar`.

    cd /path/to/your/directory
    java -jar mcpdf.jar

Alternatively, you can specify the full path to your `mcpdf.jar`.

    java -jar /path/to/your/directory/mcpdf.jar

**Comment by StCremer** [comment]
When runing [st.cremer@localhost Программирование]$ java -jar mcpdf.jar book.pdf update_info_utf8 toc.txt output newest.pdf
I get 
[st.cremer@localhost Программирование]$ java -jar mcpdf.jar Learning_Nodejs3.pdf update_info_utf8 toc.txt output newest.pdf
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/itextpdf/text/DocumentException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.itextpdf.text.DocumentException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

My system is Fedora 21

**Comment by vog** [comment]
It seems you didn't download the "jar-with-dependencies" file, but the plain JAR file instead.

**Comment by StCremer** [comment]
java.lang.RuntimeException: Unknown operation: update_info_utf8

**Comment by vog** [comment]
Currently, only `fill_form` is supported. No volunteers for the other commands have been found yet. Also note that fill_form was the main reason idea for Mcpdf, because pdftk's `fill_form` fails with several special characters.

**Comment by StCremer** [comment]
Got it) Thanks for reply anyway!
